version: '3.3'
services:
  backend:
    build:
      context: ./backend 
    ports:
      - 3333:3333
    volumes:
      - ./backend:/usr/app
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend 
    ports:
      - 3366:3366
    volumes:
      - ./frontend:/usr/app
    env_file:
      - ./.env  
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: store
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql 
volumes:
  mysql_data:
  mysql_config: